networks:
  trellis:
services:
  app:
    build:
      context: .
      dockerfile: docker/HTTPServerDockerfile
    ports:
      - "5555:5555"
    depends_on:
      - trellisredis
    environment:
      - REDIS_URL=trellisredis:6379
    networks:
      - trellis
  consumer:
    build:
      context: .
      dockerfile: docker/ConsumerDockerfile
    depends_on:
      - trellisredis
    environment:
      - REDIS_URL=trellisredis:6379
    networks:
      - trellis
  worker:
    build:
      context: .
      dockerfile: docker/WorkerDockerfile
    depends_on:
      - trellisredis
    environment:
      - REDIS_URL=trellisredis:6379
    networks:
      - trellis

  trellisredis:
  # user for storing request ids and result status
    image: redis:7-alpine
    restart: always
    ports:
      - '6381:6379'
   #  persist to disk every 2 seconds
    command: >
      redis-server 
   
      --save 2 1 
      --appendonly yes 
      --appendfilename "appendonly.aof"
      --dir /data
      --dbfilename dump.rdb
      --loglevel warning
    networks:
      - trellis
    volumes:
      - ./volumes/redis:/data:rw
  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - '8004:8001'
    depends_on:
      - trellisredis
    environment:
      - REDIS_HOST=trellisredis
      - REDIS_PORT=6379
    networks:
      - trellis

  # used for perfomatnly retrieving incoming requests
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - trellis
    volumes:
      - ./volumes/nsqlookupd:/data:rw

  nsqd1:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4151:4150"
    networks:
      - trellis
    volumes:
      - ./volumes/nsqd1:/data:rw

  nsqd2:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4152:4150"
    networks:
      - trellis
    volumes:
      - ./volumes/nsqd2:/data:rw

  nsqd3:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4153:4150"
    networks:
      - trellis
    volumes:
      - ./volumes/nsqd3:/data:rw

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    networks:
      - trellis 
